name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse current build.yml for release version
        id: yaml
        uses: the-coding-turtle/ga-yaml-parser@v0.1.1
        with:
          file: .github/workflows/build.yml
          key: jobs_docker_env_release
      - name: Create or update release tag
        uses: rickstaa/action-create-tag@v1.2.2
        with:
          tag: ${{ steps.yaml.outputs.result }}
          message: Version ${{ steps.yaml.outputs.result }}
          force_push_tag: true
